version: 2.1
jobs:
  policy-validation:
    docker:
      - image: openpolicyagent/opa:0.58.0-static
    steps:
      - checkout
      - run:
          name: Test OPA Policies
          command: opa test policies/ tests/ -v
  deploy-compliant-infrastructure:
    docker:
      - image: cimg/aws:2026.04
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_STS_REGIONAL_ENDPOINTS: global
    steps:
      - checkout
      - run:
          name: Run Lab Check
          command: |
            export AWS_ROLE_ARN='arn:aws:iam::126104434750:role/CircleCILabRole'
            export AWS_WEB_IDENTITY_TOKEN_FILE='/tmp/web-identity-token'
            echo \ > \
            aws sts get-caller-identity
workflows:
  security-pipeline:
    jobs:
      - policy-validation
      - deploy-compliant-infrastructure:
          context: aws-oidc-context
          requires:
            - policy-validation
