version: 2.1

jobs:
  policy-validation:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Clean, Download and Install OPA Binary
          command: |
            # Clean out any bad remnants first
            sudo rm -f /usr/local/bin/opa
            
            # Download using the correct github repository name (no hyphens)
            curl -L --fail -o /tmp/opa "https://github.com"
            chmod +x /tmp/opa
            sudo mv /tmp/opa /usr/local/bin/opa
      - run:
          name: Test OPA Policies
          command: |
            echo "Running OPA Unit Tests..."
            opa test policies/ tests/ -v

  deploy-compliant-infrastructure:
    docker:
      - image: cimg/aws:2026.04
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_STS_REGIONAL_ENDPOINTS: global
    steps:
      - checkout
      - run:
          name: Run Lab Check
          command: |
            export AWS_ROLE_ARN="arn:aws:iam::126104434750:role/CircleCILabRole"
            export AWS_WEB_IDENTITY_TOKEN_FILE="/tmp/web-identity-token"
            echo $CIRCLE_OIDC_TOKEN > $AWS_WEB_IDENTITY_TOKEN_FILE
            aws sts get-caller-identity

workflows:
  security-pipeline:
    jobs:
      - policy-validation
      - deploy-compliant-infrastructure:
          context: aws-oidc-context
          requires:
            - policy-validation
